from __future__ import annotations

import os
import subprocess
import sys
from pathlib import Path

def test_resolve_repository_root_uses_frozen_bundle_data_root(tmp_path: Path) -> None:
    # Given: a PyInstaller extraction location and a source-style module path.
    bundled_root = tmp_path / "frozen-bundle"
    module_path = tmp_path / "source" / "backend" / "app" / "core" / "config.py"

    # When: packaged-runtime configuration resolves its resource root.
    from app.core.config import resolve_repository_root

    actual = resolve_repository_root(module_path, bundled_root)

    # Then: deterministic rules are read from the bundled data directory.
    assert actual == bundled_root


def _config_probe(env_file: Path, overrides: dict[str, str] | None = None) -> subprocess.CompletedProcess[str]:
    environment = os.environ.copy()
    for key in tuple(environment):
        if key.startswith("IZ_CNA_") or key in {
            "ENVIRONMENT",
            "SECRET_KEY",
            "DATA_ENCRYPTION_KEY",
            "BOOTSTRAP_ADMIN_USERNAME",
            "BOOTSTRAP_ADMIN_PASSWORD",
            "LOCAL_SQLITE_DB_PATH",
        }:
            environment.pop(key)
    environment["IZ_CNA_ENV_FILE"] = str(env_file)
    environment.update(overrides or {})
    return subprocess.run(
        [
            sys.executable,
            "-c",
            (
                "from app.core.config import settings; "
                "print(settings.environment, settings.bootstrap_admin_username, "
                "settings.local_sqlite_db_path, len(settings.secret_key), "
                "len(settings.data_encryption_key))"
            ),
        ],
        cwd=Path(__file__).resolve().parents[1],
        env=environment,
        capture_output=True,
        text=True,
        check=False,
    )


def test_env_file_is_loaded_before_settings_and_generated_names_are_normalized(tmp_path: Path) -> None:
    # Given: the exact unprefixed names generated by Windows preflight.
    env_file = tmp_path / "generated.env"
    env_file.write_text(
        "\n".join(
            (
                "ENVIRONMENT=local-client",
                "SECRET_KEY=synthetic-secret-key-12345678901234567890",
                "DATA_ENCRYPTION_KEY=synthetic-data-key-12345678901234567890",
                "LOCAL_SQLITE_DB_PATH=generated.sqlite3",
                "BOOTSTRAP_ADMIN_USERNAME=localadmin",
                "BOOTSTRAP_ADMIN_PASSWORD=SyntheticBootstrapPass123",
            )
        ),
        encoding="utf-8",
    )

    # When: settings are imported in a fresh interpreter.
    result = _config_probe(env_file)

    # Then: the file values are available during global settings construction.
    assert result.returncode == 0, result.stderr
    assert result.stdout.strip() == "local-client localadmin generated.sqlite3 41 39"


def test_process_environment_overrides_env_file(tmp_path: Path) -> None:
    # Given: a safe file value and a safe explicit process override.
    env_file = tmp_path / "generated.env"
    env_file.write_text(
        "\n".join(
            (
                "ENVIRONMENT=local-client",
                "SECRET_KEY=synthetic-secret-key-12345678901234567890",
                "DATA_ENCRYPTION_KEY=synthetic-data-key-12345678901234567890",
                "BOOTSTRAP_ADMIN_USERNAME=admin",
                "BOOTSTRAP_ADMIN_PASSWORD=SyntheticBootstrapPass123",
            )
        ),
        encoding="utf-8",
    )

    # When: the process supplies the canonical prefixed administrator name.
    result = _config_probe(env_file, {"IZ_CNA_BOOTSTRAP_ADMIN_USERNAME": "overrideadmin"})

    # Then: explicit process configuration wins.
    assert result.returncode == 0, result.stderr
    assert "local-client overrideadmin" in result.stdout


def test_local_client_fails_closed_for_default_or_missing_security_values(tmp_path: Path) -> None:
    # Given: generated local-client configuration containing known unsafe defaults.
    env_file = tmp_path / "unsafe.env"
    env_file.write_text(
        "\n".join(
            (
                "ENVIRONMENT=local-client",
                "SECRET_KEY=change-me",
                "DATA_ENCRYPTION_KEY=",
                "BOOTSTRAP_ADMIN_USERNAME=admin",
                "BOOTSTRAP_ADMIN_PASSWORD=change-me",
            )
        ),
        encoding="utf-8",
    )

    # When: production settings are constructed.
    result = _config_probe(env_file)

    # Then: startup fails without echoing any supplied value.
    assert result.returncode != 0
    assert "unsafe production configuration" in result.stderr.lower()
    assert "change-me" not in result.stderr
